addReviewers: true
addAssignees: true

# (GitHub user name)
reviewers:
  - seisyll

# 0 to add all of the reviewers
numberOfReviewers: 0
# overrides
# assignees:
#   - assigneeA

# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
# numberOfAssignees: 2

# A list of keywords to be skipped the process that add reviewers if pull requests include it 
skipKeywords:
  - wip
